config/routes.rb
Rails.application.routes.draw do

  # get 'school_users/home' ビューはあるけど未定義（使えない）
  root to: 'admin_users#home'

  # 管理者関係
  resources :admin_users
  get    '/admin_login',   to: 'admin_sessions#new'
  post   '/admin_login',   to: 'admin_sessions#create'
  delete '/admin_logout',  to: 'admin_sessions#destroy'
  
  # 教室関係
  resources :school_users
  get    '/school_login',   to: 'school_sessions#new'
  post   '/school_login',   to: 'school_sessions#create'
  delete '/school_logout',  to: 'school_sessions#destroy'
  
  # 講師関係
  resources :teacher_users
  get    '/teacher_login',   to: 'teacher_sessions#new'
  post   '/teacher_login',   to: 'teacher_sessions#create'
  delete '/teacher_logout',  to: 'teacher_sessions#destroy'
  
  
  # 生徒関係
  resources :student_users
  get    '/login',   to: 'student_sessions#new'
  post   '/login',   to: 'student_sessions#create'
  delete '/logout',  to: 'student_sessions#destroy'
  
  
  
  
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if admin_logged_in? %>
          <li><%= link_to "ユーザー一覧", admin_users_path %></li>
          <li><%= link_to "Profile", current_admin_user %></li>
          <li><%= link_to "プロフィール編集", edit_admin_user_path(current_admin_user) %></li>
          <li><%= link_to "管理者Log out", admin_logout_path, method: :delete %></li>
        <% elsif school_logged_in? %>
          <li><%= link_to "登録教室一覧", school_users_path %></li>
          <li><%= link_to "教室情報", current_school_user %></li>
          <li><%= link_to "教室情報編集", edit_school_user_path(current_school_user) %></li>
          <li><%= link_to "教室Log out", school_logout_path, method: :delete %></li>
        <% elsif student_logged_in? %>
          <li><%= link_to "登録生徒一覧", student_users_path %></li>
          <li><%= link_to "生徒情報", current_student_user %></li>
          <li><%= link_to "生徒情報編集", edit_student_user_path(current_student_user) %></li>
          <li><%= link_to "生徒Log out", logout_path, method: :delete %></li>
        <% elsif teacher_logged_in? %>
          <li><%= link_to "登録講師一覧", teacher_users_path %></li>
          <li><%= link_to "講師情報", current_teacher_user %></li>
          <li><%= link_to "講師情報編集", edit_teacher_user_path(current_teacher_user) %></li>
          <li><%= link_to "講師Log out", teacher_logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "生徒用Log in", login_path %></li>
          <li><%= link_to "管理者用Log in", admin_login_path %></li>
          <li><%= link_to "教室用Log in", school_login_path %></li>
          <li><%= link_to "講師用Log in", teacher_login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ScheduleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <p><%= link_to "student_userのサインアップページ", new_student_user_path %></p>
    <p><%= link_to "admin_userのサインアップページ", new_admin_user_path %></p>
    <p><%= link_to "school_userのサインアップページ", new_school_user_path %></p>
    <p><%= link_to "techer_userのサインアップページ", new_teacher_user_path %></p>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>